// Generated by IcedCoffeeScript 1.2.0i
(function() {
  var dub, iced, main, __iced_k;

  iced = require('iced-coffee-script').iced;
  __iced_k = function() {};

  dub = function(n, cb) {
    return setTimeout((function() {
      return cb(n * 2);
    }), 2000);
  };

  main = function() {
    var v, v2, ___iced_passed_deferral, __iced_deferrals,
      _this = this;
    ___iced_passed_deferral = iced.findDeferral(arguments);
    (function(__iced_k) {
      __iced_deferrals = new iced.Deferrals(__iced_k, {
        parent: ___iced_passed_deferral,
        filename: 'iced.coffee',
        funcname: 'main'
      });
      dub(10, __iced_deferrals.defer({
        assign_fn: (function() {
          return function() {
            return v = arguments[0];
          };
        })(),
        lineno: 6
      }));
      __iced_deferrals._fulfill();
    })(function() {
      (function(__iced_k) {
        __iced_deferrals = new iced.Deferrals(__iced_k, {
          parent: ___iced_passed_deferral,
          filename: 'iced.coffee',
          funcname: 'main'
        });
        dub(v, __iced_deferrals.defer({
          assign_fn: (function() {
            return function() {
              return v2 = arguments[0];
            };
          })(),
          lineno: 8
        }));
        __iced_deferrals._fulfill();
      })(function() {
        return console.log("result (in callback) of dub(10) ** 2:", v2);
      });
    });
  };

  main();

  console.log("this runs first");

}).call(this);
